## Exploring the use of NMF (Non-negative Matrix Factorization) as a dimension reduction technique

In [6]:
## Loading the dataset in csr format
import pandas as pd
from scipy.sparse import csr_matrix

df = pd.read_csv('wikipedia-vectors.csv', index_col=0)
articles = csr_matrix(df.transpose())
titles = list(df.columns)

words = []
# Read words form the file

for line in open('wikipedia-vocabulary-utf8.txt', 'r', encoding='utf-8'):
        word = line.strip()
        words.append(word)
    
    
        

In [7]:
words

['aaron',
 'abandon',
 'abandoned',
 'abandoning',
 'abandonment',
 'abbas',
 'abbey',
 'abbreviated',
 'abbreviation',
 'abc',
 'abdomen',
 'abdominal',
 'abdul',
 'abel',
 'abilities',
 'ability',
 'able',
 'abnormal',
 'abnormalities',
 'abnormally',
 'aboard',
 'abolish',
 'abolished',
 'abolishing',
 'abolition',
 'aboriginal',
 'abortion',
 'abraham',
 'abroad',
 'abrupt',
 'abruptly',
 'absence',
 'absent',
 'absolute',
 'absolutely',
 'absorb',
 'absorbed',
 'absorbing',
 'absorbs',
 'absorption',
 'abstract',
 'abstraction',
 'absurd',
 'abu',
 'abundance',
 'abundant',
 'abuse',
 'abused',
 'abuses',
 'abusive',
 'academia',
 'academic',
 'academics',
 'academies',
 'academy',
 'accelerate',
 'accelerated',
 'accelerating',
 'acceleration',
 'accent',
 'accents',
 'accept',
 'acceptable',
 'acceptance',
 'accepted',
 'accepting',
 'accepts',
 'access',
 'accessed',
 'accessible',
 'accessing',
 'accession',
 'accessories',
 'accessory',
 'accident',
 'accidental',
 'accidenta

In [ ]:
# Import NMF
from sklearn.decomposition import NMF

# Create an NMF instance: model
model = NMF(n_components=6) # Number of topics
# Set n_components to the number of topics you want to extract

# Fit the model to articles
model.fit(articles)

# Transform the articles: nmf_features
nmf_features = model.transform(articles)

# Print the NMF features
print(nmf_features.round(2))


[[0.   0.   0.   0.   0.   0.44]
 [0.   0.   0.   0.   0.   0.56]
 [0.   0.   0.   0.   0.   0.4 ]
 [0.   0.   0.   0.   0.   0.38]
 [0.   0.   0.   0.   0.   0.48]
 [0.01 0.01 0.01 0.03 0.   0.33]
 [0.   0.   0.02 0.   0.01 0.36]
 [0.   0.   0.   0.   0.   0.49]
 [0.02 0.01 0.   0.02 0.03 0.48]
 [0.01 0.03 0.03 0.07 0.02 0.34]
 [0.   0.   0.53 0.   0.03 0.  ]
 [0.   0.   0.35 0.   0.   0.  ]
 [0.01 0.01 0.31 0.06 0.01 0.02]
 [0.   0.01 0.34 0.01 0.   0.  ]
 [0.   0.   0.43 0.   0.04 0.  ]
 [0.   0.   0.48 0.   0.   0.  ]
 [0.01 0.02 0.37 0.03 0.   0.01]
 [0.   0.   0.48 0.   0.   0.  ]
 [0.   0.01 0.55 0.   0.   0.  ]
 [0.   0.   0.46 0.   0.   0.  ]
 [0.   0.01 0.02 0.51 0.06 0.01]
 [0.   0.   0.   0.51 0.   0.  ]
 [0.   0.01 0.   0.42 0.   0.  ]
 [0.   0.   0.   0.43 0.   0.  ]
 [0.   0.   0.   0.49 0.   0.  ]
 [0.1  0.09 0.   0.38 0.   0.01]
 [0.   0.   0.   0.57 0.   0.01]
 [0.01 0.01 0.   0.47 0.   0.01]
 [0.   0.   0.   0.57 0.   0.  ]
 [0.   0.   0.   0.52 0.01 0.01]
 [0.   0.4

### Exploring the constructed components

In [ ]:
import pandas as pd

# Create a pandas DataFrame: df
df = pd.DataFrame(nmf_features,index=titles)

# Print the row for 'Anne Hathaway'
print(df.loc['Anne Hathaway'])

# Print the row for 'Denzel Washington'
print(df.loc['Denzel Washington'])


0    0.003815
1    0.000000
2    0.000000
3    0.571858
4    0.000000
5    0.000000
Name: Anne Hathaway, dtype: float64
0    0.000000
1    0.005574
2    0.000000
3    0.419558
4    0.000000
5    0.000000
Name: Denzel Washington, dtype: float64


#### *NMF components represent topics when applied to a document. NMF features combine topics into documents.
#### For images, NMF components represents patterns or parts of image.

In [8]:
# Import pandas
import pandas as pd

# Create a DataFrame: components_df
components_df = pd.DataFrame(model.components_,columns=words)

# Print the shape of the DataFrame
print(components_df.shape)

# Select row 3: component
component = components_df.iloc[3,:]

# Print result of nlargest
print(component.nlargest())

(6, 13125)
film       0.632114
award      0.254838
starred    0.246940
role       0.212878
actress    0.187655
Name: 3, dtype: float64


### As saw previously, 3rd feature was most important for Denzel and Anne, and this shows that the topics were related to their field 

### Building Article Recommender System using NMF 

In [9]:
# Perform the necessary imports
import pandas as pd
from sklearn.preprocessing import normalize

# Normalize the NMF features: norm_features
norm_features = normalize(nmf_features)

# Create a DataFrame: df
df = pd.DataFrame(norm_features,index=titles)

# Select the row corresponding to 'Cristiano Ronaldo': article
article = df.loc['Cristiano Ronaldo']

# Compute the dot products: similarities
similarities = df.dot(article)

# Display those with the largest cosine similarity
print(similarities.nlargest())

Cristiano Ronaldo                1.000000
Franck Ribéry                    0.999973
Radamel Falcao                   0.999942
Zlatan Ibrahimović               0.999942
France national football team    0.999923
dtype: float64


This uses cosine similarity to find closely related topics to Cristiano Ronaldo, and it does find pretty close topics!!

## Recommending Muscial Artists using NMF

In [41]:
# Import artist data 
import numpy as np


artists_array = np.zeros((111, 500), dtype=int)
for line in open('Musical artists/scrobbler-small-sample.csv', 'r', encoding='utf-8'):
    if line.startswith('user_offset'):
        continue  # Skip header line
    col, row, data = line.strip().split(',')
    artists_array[int(row), int(col)] = int(data)

print(artists_array.shape)
print(artists_array)

artists = csr_matrix(artists_array)
print(artists)
df_names = pd.read_csv('Musical artists/artists.csv', header=None)
artist_names = df_names.iloc[:,0].values

(111, 500)
[[  0   0 105 ...   0   0   0]
 [128 211   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0  55   0]
 [  0   0   0 ...   0   0   0]]
  (0, 2)	105
  (0, 15)	165
  (0, 20)	91
  (0, 21)	98
  (0, 29)	120
  (0, 48)	236
  (0, 70)	67
  (0, 95)	77
  (0, 96)	93
  (0, 109)	98
  (0, 113)	63
  (0, 126)	63
  (0, 127)	429
  (0, 130)	151
  (0, 132)	103
  (0, 152)	83
  (0, 153)	65
  (0, 162)	54
  (0, 181)	456
  (0, 183)	592
  (0, 186)	111
  (0, 193)	158
  (0, 194)	53
  (0, 195)	216
  (0, 201)	89
  :	:
  (109, 444)	82
  (109, 450)	271
  (109, 467)	107
  (109, 472)	130
  (109, 478)	776
  (109, 483)	66
  (109, 498)	55
  (110, 56)	51
  (110, 60)	272
  (110, 119)	156
  (110, 149)	87
  (110, 165)	112
  (110, 291)	104
  (110, 325)	183
  (110, 345)	106
  (110, 358)	80
  (110, 360)	111
  (110, 361)	57
  (110, 414)	92
  (110, 429)	60
  (110, 433)	388
  (110, 460)	66
  (110, 463)	105
  (110, 465)	128
  (110, 468)	69


In [42]:
artists.toarray().shape
print(len(artist_names))

111


In [43]:
# Perform the necessary imports
from sklearn.decomposition import NMF
from sklearn.preprocessing import Normalizer, MaxAbsScaler
from sklearn.pipeline import make_pipeline

# Create a MaxAbsScaler: scaler
scaler = MaxAbsScaler()

# Create an NMF model: nmf
nmf = NMF(n_components=20)

# Create a Normalizer: normalizer
normalizer = Normalizer()

# Create a pipeline: pipeline
pipeline = make_pipeline(scaler,nmf,normalizer)

# Apply fit_transform to artists: norm_features
norm_features = pipeline.fit_transform(artists)


### Here we recommend artists most similar to Bruce Springsteen

In [44]:
# Import pandas
import pandas as pd

# Create a DataFrame: df
df = pd.DataFrame(norm_features,index=artist_names)

# Select row of 'Bruce Springsteen': artist
artist = df.loc['Bruce Springsteen']

# Compute cosine similarities: similarities
similarities = df.dot(artist)

# Display those with highest cosine similarity
print(similarities.nlargest())


Bruce Springsteen    1.000000
Leonard Cohen        0.963038
Neil Young           0.951583
The Beach Boys       0.857650
Van Morrison         0.843219
dtype: float64
